Channels:
- baseDir: /path/to/shows/
  id: 0
  name: TV Channel
  showDirs:
  - Show Directories
- baseDir: /path/to/movies
  id: 1
  name: Movie Channel
DVR:
  friendlyName: PyPlexDVR
  tunerCount: 100
EPG:
  TMDBAPIKey: API Key
  generate: true
Server:
  bindAddr: 127.0.0.1
  bindPort: '5004'
