Channels:
- baseDir: /path/to/shows/
  id: 0
  name: TV Channel
  showDirs:
  - Show Directories
- baseDir: /path/to/movies
  id: 1
  name: Movie Channel
Streams:
  - name: BBC One North West
    id: 2
    url: https://vs-cmaf-pushb-uk-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_one_north_west/pc_hd_abr_v2.mpd
DVR:
  friendlyName: PyPlexDVR
  tunerCount: 100
EPG:
  TMDBAPIKey: API Key
  generate: true
Server:
  bindAddr: 127.0.0.1
  bindPort: '5004'
